import Head from "next/head";
import { randAddress, randEmail, randFullName, randIban } from "@ngneat/falso";
import { useEffect, useState } from "react";
import Checkbox from "@mui/material/Checkbox";
import { styled } from "@mui/material/styles";

type arrayObjects = {
  street: string;
  city: string;
  zipCode: string;
  county: string;
  country: string;
};

export default function Home() {
  const [emails, setEmails] = useState<string[]>([]);
  const [names, setNames] = useState<string[]>([]);
  const [ids, setIds] = useState<string[]>([]);
  const [adresses, setAdresses] = useState<arrayObjects[]>([]);

  const Div = styled("div")(({ theme }) => ({
    ...theme.typography.button,
    backgroundColor: theme.palette.background.paper,
    padding: theme.spacing(1),
  }));

  useEffect(() => {
    setEmails(randEmail({ length: 100 }));
    setNames(randFullName({ length: 100 }));
    setIds(randIban({ length: 100 }));
    setAdresses(randAddress({ length: 100 }));
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className=""
        style={{ display: "flex", justifyContent: "space-between" }}
      >
        <Div className="">
          {emails.map((email) => {
            return (
              <div key={email} className="">
                {email}
              </div>
            );
          })}
        </Div>
        <Div className="">
          {names.map((name) => {
            return (
              <div key={name} className="">
                {name}
              </div>
            );
          })}
        </Div>
        <Div className="">
          {ids.map((id) => {
            return (
              <div key={id} className="">
                {id}
              </div>
            );
          })}
        </Div>
        <Div className="">
          {adresses.map((adress) => {
            return (
              <div key={adress.street} className="">
                {adress.street}
              </div>
            );
          })}
        </Div>
        <Div className="">
          {adresses.map((adress) => {
            return (
              <div key={adress.city} className="">
                {adress.city}
              </div>
            );
          })}
        </Div>
        <Div className="">
          {adresses.map((adress) => {
            return (
              <div
                key={adress.zipCode}
                className=""
                style={{ height: "24.5px" }}
              >
                {adress.zipCode}
                <Checkbox style={{ padding: "0" }} />
              </div>
            );
          })}
        </Div>
      </div>
    </div>
  );
}
